### ISSUE TITLE
[Feature]: Termux Variable support

### ISSUE THREAD

**Issue by JeelsBoobz** [termux-play-store/termux-apps#15]
### Feature description

Temux variable like F-Droid version

### Additional information

![Screenshot_2024-06-15-08-41-48-077_com termux](https://github.com/termux-play-store/termux-apps/assets/38210868/f5c3e07e-a156-4513-b8dd-41e4db01b399)

**Comment by fornwall** [comment]
Thanks for reporting!

The next update, version `0.127`, will start exporting the `TERMUX_VERSION` environment variable, just like the F-Droid build does.

So at least `TERMUX_VERSION=x.yzw` will be shown there instead of `unsupported` - are there any additional specific variable you need there, or is the version one the main driver?

**Comment by fornwall** [comment]
Closing this as termux variables now show up after `pkg up`. Please create a new issue if there is anything related that you think needs improvement.

Once again, thanks for reporting the issue!
